name: Firewall Rules Action
description: Updates the firewall rules on Hetzner Cloud to use the current Github action runner's IP address
inputs:
  api-token:
    description: Hetzner Cloud API token
    required: true
  firewall-id:
    description: The ID of the firewall to update (You can find this in the Hetzner Cloud Console in your browser address bar)
    required: true
runs:
  using: node20
  pre: code/initialize.js
  main: code/modify.js
  post: code/restore.js
